/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:1023fe57-d432-4b87-a6a8-4c388d19689b",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_gShzb5chR",
    "aws_user_pools_web_client_id": "5iu362celirmkntuqdenp0u8bt",
    "oauth": {}
};


export default awsmobile;
